### ISSUE TITLE
"searchAs" Not Always Work?

### ISSUE THREAD

**Issue by av2000ii** [gdh1995/vimium-plus#1]
Thanks for your excellent extension :100: . 

1. 

But I found "searchAs" not always work, Many times it just tell me "no search engine found!"(I use 360极速浏览器 8.7.0.306 内核50.0.2661.102). BTW I am use the default search engine settings(Baidu).

2. 

I'm noticed that vimium plus supports session function. Is it mean I can store opened tabs?If so, how can I use it? I cant find it in settings.

3. 

Just a suggestion, Can you make vimium plus to view Tab history(as we right click the back/forward button on browser UI) in vomnibar? It is very useful when we forget what we have opened with one tab, not like the whole history with all tabs what have been opened.

**Comment by gdh1995** [comment]
Do you mainly speak Chinese?

**Comment by gdh1995** [comment]
## 1
When you map `searchAs` / `searchInAnother`, the command should be like:
```
map Gb searchInAnother keyword="b"
```

The `keyword` must be a valid "custom search engine". For example, the text below declares some search engines named "b", "吧", "ba", ..., and "百度":
```
b|吧|把|ba|bd|baidu|Baidu|百度: https://www.baidu.com/s?ie=UTF-8&wd=$s
```

Vimium++ will try its best to parse the url `https://www.baidu.com/s?ie=UTF-8&wd=$s` and learn how to extract your keywords from your current tab's url. For one line `b: https://www.baidu.com/s?ie=UTF-8&wd=$s`, keywords may be got if a tab's url meets:
* it starts with `https://www.baidu.com/s`
* its query includes a sub-string looking like "wd=XXXX%XX%XX%XXYYYZZZ"
* that is, its query includes a key named `wd`
* the value will be decoded using UTF-8, so `a%20b%E7%99%BE%E5%BA%A6` will make `a b百度`

And if the value is found (even if it's empty), Vimium++ will do further actions.

## 2
You need to add a key mapping `map z restoreTab`, and then press `z` to restore the last closed tab.

## 3
Chrome's extension platform does not allow any extensions to access tab's history.

**Comment by av2000ii** [comment]
> Do you mainly speak Chinese?
是的。

谢谢您详细的回复，我已经弄明白了！对于我提的第二个问题，也就是说vimium plus可以支持在含有搜索引擎的页面中搜索selected text，如果没有相应的搜索引擎的页面则该功能是不可用的。

我还有两个想法：
- Add function to quick delete the content in input box(such as `<ctrl-d>` )

- Add option to toggle help popup(the help displayed when type "`?`") . Maybe that's can minimize the impact of page rendering, and makeing vimium plus faster.

**Comment by gdh1995** [comment]
浪费了我的中学英语啊。。。还是打汉字快些。

1. 搜索引擎(Custom search engines)需要你自己配置，也可以用Vimium++选项页面的“Import Settings”右边的下拉按钮，选择“Recommended”来直接导入我常用的设置，里边有百度/bing/Google和mdn之类的搜索模式，匹配能力更好（因为Custom search engines里支持自定义`[prefix, regExp, splitter]`来任意匹配URL

2. 快速删除所有文本的话，ctrl+A 然后 delete/backspace就行了吧，实现上有点麻烦的是：
* 如果网页的焦点在文本框，那么原版的Vimium会不激活所有快捷键，而我的Vimium++只允许包含的F1~F12快捷键
  * 比如我常用设置里，<f1> 是映射到了backspace，<F1> (shift+f1)是blur/re-focus
* 因此如果确实需要，要么你Ctrl+A后按F1（单手的时候有意义，否则还不如右手去按backspace快）；
* 要么需要增加一个命令来选中当前框的所有文本，然后删除，但我觉得你这个需求太小而且太弱了。。。

3. `toggle help popup`? 你是说缓存HelpDialog然后留到下次按'?'的时候再直接显示，而不再重新渲染吗？其实影响不大了，我这里HelpDialog只是个`<div>`，而不像原版Vimium那样开个`<iframe>`。我的考虑有这些：
* 目前，Vimium++里content scripts（在任意网页里执行的前端脚本）只向后台进程请求所有被map的键，而没有获取完整的键盘映射的信息
  * 前端每次触发命令时给后台发信息来获取命令的参数之类的，平时不维护各命令的参数/描述
  * 如果在设置页面里修改了key mappings，前端会更新键映射方案，但仍然不包括参数
* 因此，每次按`?`的时候，要确保显示的对话框是正确的，就要向后台查询是否有变化，万一变了还要再同步
* 而后台进程确实可以缓存help页面，并且在每次修改key mappings的时候重置掉
* 但我觉得吧，帮助对话框不常用，就算真的是一阵子里要经常打开它，完全可以变成：
  * 克隆当前页面（A）得到B，Vimium++的命令是duplicateTab，我自己映射到了ctrl+shift+D
  * 在A页面里打开帮助对话框，不再关闭它，在B页面里做别的事情

PS：如果你只在Vimium++的设置页面里按过`?`来打开帮助对话框，那么你可以试试在别的页面按`?`，默认配置和推荐配置里`?`都是对应 showHelp 这个command.
