### ISSUE TITLE
map按键无效？

### ISSUE THREAD

**Issue by ffplayer** [gdh1995/vimium-plus#10]
`map 1 previousTab
map 2 nextTab
map 3 removeTab
map c duplicateTab
map e scrollPageDown
map q scrollPageUp
map 4 reload
map r restoreTab
map d goForward
map a goBack
map z goPrevious
map x goNext
map h searchAs keyword="3b"`
自定义搜索：
`a|3b: http://www.3bsou.com/s?keyword=$s&ie=utf-8&left=baidu&right=google&opt=web&num=20&xz=2`

感谢作者@gdh1995 在vimium的issue下的回复，问题直接提到这里好了。我下载了vimium-plus然后如上定义了习惯的按键并且save changes，但是发现都无效呢？
像eq有效应该是跟默认的等同所以仍然有效。自己改过的都不行。 比如按1、2、3都没反应，按x仍然是关闭当前tab。
最后自定义的h搜索也还是没用(按o键输入搜索引擎别名是可以调用搜索的)。。

求问是我哪里搞错了 0.0
chrome版本 59.0.3071.115（正式版本） （64 位）

**Comment by ffplayer** [comment]
> Prefix Count Arguments
> As in vim, many Vimium commands accept a prefix count argument. For example, K moves one  tab to the right, so 3K moves three tabs to the right.

看了vimium的说明，发现了这个，数字键无法单独映射是因为这个原因么（被当成了Prefix Count Argument）？有办法可以解决么？

**Comment by gdh1995** [comment]
数字键确实是这个问题，没办法，逻辑写死了。

x 的问题我看看啊

**Comment by gdh1995** [comment]
x和h的问题找到了，Vimium和Vimium++有默认的key mapping，然后键绑定的逻辑是一旦h被绑定过，后边的map h ...就不会生效。

你可以写:
```
unmap h
map h searchAs keyword="3b"
```

商店里的Vimium++ 1.60.1已经能显示key mapping有没有错误了，保存后背景变淡红色则表示有问题，可以去chrome://extensions/?id=hfjbmagddngcpeloejdejnfgbamkjaeg点“检查视图：背景页”来看控制台报错日志。

你这提醒我了，过几天我再处理处理，争取把错误信息显示到配置页面里。

**Comment by ffplayer** [comment]
原来还要先unmap一下才行~  感谢~~

**Comment by transtone** [comment]
vimium 是可以单独映射数字键的，vimium-c 不能，什么时候可以升级一下吗？

**Comment by gdh1995** [comment]
目前设计上如此，因为我觉得没必要支持数字键作为独立命令。事实上Vimium C 绝大多数命令都支持按数字前缀来执行不同任务，如果某个数字键被占用了，感觉需要的时候就很容易误操作。

**Comment by gdh1995** [comment]
顺带，现在`map`命令已经能识别默认的命令绑定了，所以如果之前没手动设置过"map h"，那就不需要写"unmap h"再跟一个”map h ...“了。只在和已经手动map过的按键序列重复时才会报错（显示淡红色背景）。

**Comment by transtone** [comment]
主要是想跟 opera 的快捷键一致。opera 用 1,2 两个键来做导航，非常方便。

**Comment by gdh1995** [comment]
@transtone 现在应该可以用`mapKey`配合操作：

```
mapKey 1 !
mapKey 2 @
map ! goBack
map @ goForward
```

代价是count里再也不能用1和2了，即使有别的数字前缀了也不行。
