### ISSUE TITLE
New tab opens non-momentum page

### ISSUE THREAD

**Issue by jordy-wijman** [gdh1995/vimium-plus#14]
I've got the extension Momentum installed and that replaces the new tab page. But whenever I press 'T' to open a new tab, it won't open the momentum page.

Expected page:
![image](https://user-images.githubusercontent.com/18186115/35912607-58be5bfe-0bfd-11e8-9d28-cec1adfff601.png)

Result after pressing 'T':
![image](https://user-images.githubusercontent.com/18186115/35914747-b0184804-0c04-11e8-97bd-c77c357725bc.png)

**Comment by gdh1995** [comment]
Now you need to set the"New Tab URL" option of Vimium++, and it should be the other extension's page URL. More details are in https://github.com/gdh1995/vimium-plus/wiki/Use-another-extension-as-the-New-Tab

**Comment by jordy-wijman** [comment]
@gdh1995 Ah right, excuse me I missed that tutorial in the wiki! The issue has been resolved.
