### ISSUE TITLE
Error Loading Unpacked

### ISSUE THREAD

**Issue by akai1831** [gdh1995/vimium-plus#18]
Hi, @gdh1995 . Howdy? I couldn't load the downloaded Vimium++ from the browser see error below. Could you update your plugin in Web Store. Thanks!
![vimium](https://user-images.githubusercontent.com/20372600/39201837-f0893fa8-47f8-11e8-99b1-477e2da27bc6.JPG)

**Comment by gdh1995** [comment]
You need to "build" this project first, which means you must use node.js, npm and gulp. If you don't know what they're, you may visit Chrome Web Store and search and install Vimium++ from there.

If you know some about frontend development, you can run the follow commands in terminal on the project folder:
* npm install
* gulp local

Then the folder can be imported as a Chrome extension.
