### ISSUE TITLE
使用F点击链接未在后台打开

### ISSUE THREAD

**Issue by iliuyuyang** [gdh1995/vimium-plus#2]
默认状态下vimium的f和F逻辑是"在当前标签页打开链接"和"新建标签并在后台打开链接"，但在使用vimium++的时候感觉存在bug，使用F不是新建标签并在后台打开，而是新建标签后跳转到新建的标签。

重新绑定LinkHints.activateModeToOpenInNewTab后未解决问题，感觉是函数有错误。

**Comment by gdh1995** [comment]
能说下你用的Vimium++的版本、是哪个url上的哪个超链接吗？

**Comment by iliuyuyang** [comment]
基本上是所有超链接哦。使用的是        58.0.3014.0（正式版本）canary （64 位）

**Comment by gdh1995** [comment]
使用的是Vimium++的master版还是应用商店版？版本号显示的是1.58beta吗？

**Comment by iliuyuyang** [comment]
应用商店版 1.58beta

**Comment by gdh1995** [comment]
我刚在Chrome 58.0.3013.0 x64上测试了master 和 应用商店版，在空配置时`F`正常，在推荐配置的下`Fg`正常。测试页面是https://m.baidu.com/?pu=sz%401328_100

**Comment by iliuyuyang** [comment]
发了一段视频到你邮箱里面，你看下吧。我这边用的mac，难道是这的原因吗？

**Comment by iliuyuyang** [comment]
经测试这问题在window下的chrome不存在，应该是系统差异。

**Comment by gdh1995** [comment]
我没收到邮件，mac我没法测试，你可以用developer tools来debug下content/link_hints.js里的DEFAULT.activator，看看this.mode和onMac是多少。

Vimium判断了Mac系统，如果是mac则会使用metaKey，windows下用ctrlKey，来模拟单击链接。你试试你的Mac下“metaKey+鼠标左键单击”能不能触发”后台创建新标签页打开网址“吧。

**Comment by iliuyuyang** [comment]
确实是你说的原因，我fork一个来改改，谢谢了。

**Comment by gdh1995** [comment]
这个地方不太好轻易改，你能测试下Chrome55/56下的情况吗？需要确定这个问题是一直有还是某些个Chrome版本后才有。而且金丝雀/dev版改动很频繁，有可能过几天这个问题就被Chrome给抹平成不存在了，最好在stable版本上确认下。

**Comment by gdh1995** [comment]
另外这个项目现在用了typescript，如果你不方便安装，可以把1.57.6这个tag给checkout出来，那个版本应该还是全javascript的，然后再修改。

另一种方式是，把github上release的1.57.6的crx文件解压了，然后改js文件，改好之后再去改git仓库里对应的位置并提交。

或者就安装typescript吧，不过官方的typescript在编译的时候会报一些error，不用管。

**Comment by iliuyuyang** [comment]
稳定版中测试问题依然存在，应该是win和osx的键位设置不同所致。

**Comment by gdh1995** [comment]
这个问题其实是我写的代码里存在竞态条件，实际启动中先判断了平台是否是Mac，才用getPlatformInfo获取了平台信息，很明显这是个大问题。新commit里修复了。

PR #5 里用userAgent来判断是否是Mac，这个方法不能百分百保证正确，因为可以强行在开发者工具里修改Network conditions里的user agent。

这也是为什么不能在content scripts里直接用userAgent判断是不是mac，毕竟Chrome里后台环境隔离得好，更安全些。

Close #5
