### ISSUE TITLE
Can't work in some ext I installed.

### ISSUE THREAD

**Issue by TYZRPVX** [gdh1995/vimium-plus#21]
Can't work in some ext I installed, such as tampermonkey.

**Comment by gdh1995** [comment]
This extension can only run on those extensions which have declare themselves support Vimium++. And on Vimium++ Options page, you must add IDs of target extensions into the "white list of ...".

So, what's the ID (or URL on Web Store) of your mentioned extension?

**Comment by TYZRPVX** [comment]
Thanks for your timely reply, the extension id is dhdgffkkebhmkfjojejmpbldmpobfkfo, which I added to whitelist. However, I can't run Vimium++ in its setting page `chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/options.html#nav=settings `

**Comment by gdh1995** [comment]
The extension Tampermonkey is a popular extension and has no official support for Vimium++. If you indeed want to use Vimium++ on its options page, here's a tutorial to modify this extension by yourself: https://github.com/gdh1995/vimium-plus/wiki/Inject-into-other-extensions

**Comment by TYZRPVX** [comment]
Thanks a lot.
