### ISSUE TITLE
弹出搜索框之后，按esc键搜索框消失之后，再按任何键，界面无反应

### ISSUE THREAD

**Issue by ShengboZhang** [gdh1995/vimium-plus#4]
浏览器版本：56.0.2924.87 (64-bit)
vimium++版本：1.58 beta

**Comment by gdh1995** [comment]
这个问题已经修复了，请更新Vimium++试试。

问题出在Chrome的“进程外 iframe”（"#enable-site-per-process"）这个特性上，Chrome56之后这个特性好像会时不时自动被启用，尽管我从设置界面上看这个始终是关着的

**Comment by gdh1995** [comment]
基本确定了是Chrome从56开始，对扩展应用的iframe自动开启site-per-processss效果，也就是把那些页面挪到扩展应用的进程里。此问题在1.58.0版本已修复。
