### ISSUE TITLE
Trying to inject vimium++ into pdfviewer

### ISSUE THREAD

**Issue by KVohra95** [gdh1995/vimium-plus#7]
Hi

I tried to do the implementing of the vimium++ plugin into Pdf.js - https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm?hl=en  by editing the html and adding

<script src="chrome-extension://hfjbmagddngcpeloejdejnfgbamkjaeg/lib/injector.js">

to the html but this doesnt seem to work.

Is there any way you can test this and see if it works?

Thanks

Kabeer

**Comment by KVohra95** [comment]
for some reason, new lines are not working in this, sorry for the poor formatting

**Comment by KVohra95** [comment]
Edited the plugin to get the script injected but I am getting this error, any idea how to add vimium to the whitelist?

    Vimium++: fail to inject into lkgmegojdfkgicmiccialdonokdlopoe : not in the white list.

**Comment by gdh1995** [comment]
Well, sorry for my old and too short documents.

The error means you need to add the extension id of your Pdf.js into Vimium++'s injection white list. The list is at the bottom of Vimium++'s options page.

Thanks for your approval!

By the way, if you're using a new version of Chrome (>=55), then Chrome has changed its CSP rules and you'll have to modify the CSP contents in the manifest.json

**Comment by KVohra95** [comment]
It works! I have been trying to get vimium working on pdf tabs for ages, thank you!

**Comment by gdh1995** [comment]
Solved, so closed.
