### ISSUE TITLE
Map keys on passthrough and mapping backspace key

### ISSUE THREAD

**Issue by KVohra95** [gdh1995/vimium-plus#8]
Hi,

I was wondering if two things were possible.

The first think is to map the keys on passthrough, is this possible? For example if I want G to send a B to the underlying website.

The second thing is in the mappings, is it possible to map non-ascii keys like the backspace key? I would like to map the backspace key to go back a page for example.

Thanks

Kabeer

**Comment by gdh1995** [comment]
1. Vimium++ is not allowed to simulate real keyboard events.

2. `map <backspace> goBack` should work.

**Comment by gdh1995** [comment]
@KVohra95 Have the 2 questions been solved?

**Comment by gdh1995** [comment]
Closed. If there're still any issues, please let me know. Thanks.
